#!/bin/bash

# set variables:
EXITV=0
KERNELREL=$(uname -r)
NUMCORES=$(lscpu --parse=core|sed '/^#/ d'|sort -u|wc -l)
NUMCPUS=$(lscpu --parse=core|sed '/^#/ d'|wc -l)

if cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor|grep -q powersave; then
    echo "Problem: At least one CPU is running in powersave mode."
    echo "Suggestion: Use \"sudo tascar_cpufreq\" to switch all CPUs to performance mode."
    echo ""
    let EXITV=$EXITV+1
fi
if !(echo $KERNELREL|grep -q -e realtime -e lowlatency); then
    echo "Problem: The kernel release is ${KERNELREL}, which does not provide real-time scheduling."
    echo "Suggestion: Install and boot realtime kernel."
    echo ""
    let EXITV=$EXITV+2
fi
if test "${NUMCORES}" -ne "${NUMCPUS}"; then
    echo "Problem: The system reports ${NUMCPUS} CPUs, but only ${NUMCORES} physical cores."
    echo "Suggestion: Disable HyperThreading in BIOS."
    echo ""
    let EXITV=$EXITV+4
fi
if id -nG | grep -v -q 'audio'; then
    echo "Problem: You are not a member of the 'audio' group."
    echo "Suggestion: Add user to 'audio' group (see tascar manual)."
    echo ""
    let EXITV=$EXITV+8
fi
if test $(ulimit -r) -le 90; then
    echo "Problem: Your limit for real-time priority is $(ulimit -r)."
    echo "Suggestion: Edit /etc/security/limits.conf accordingly and re-login."
    echo ""
    let EXITV=$EXITV+16  
fi
if test $EXITV == 0; then
    echo "Congratulations!"
    echo "Your system seems to be optimised for low-delay audio processing."
fi
exit $EXITV
