name: MacOS make

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: fetchall
      run: git fetch --unshallow --tags
    - name: github-cmake workaround
      run: brew uninstall cmake
    - name: dependencies1
      run: brew install pkgconfig coreutils labstreaminglayer/tap/lsl
    - name: dependencies2
      run: brew install jack liblo libsndfile eigen boost gsl fftw libsamplerate xerces-c libltc libmatio cunit
    - name: dependencies3
      run: brew install glibmm gtkmm3 gtksourceviewmm3 adwaita-icon-theme
    - name: dependencies4
      run: brew install jpeg
    - name: lookforlsl in usr
      run: find /usr/ -name lsl_cpp.h || true
    - name: lookforlsl in opt
      run: find /opt/ -name lsl_cpp.h || true
    - name: make
      run: make -j 4
    - name: test
      run: make unit-tests test
